name: Test

on:
    push:
      branches: [ '**' ]
    pull_request:
      branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Download NATS server
        run: npm run postinstall

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
